# the __init__ method generated by @dataclass only takes the arguments passed
# and assigns them. What if you want to do something extra during __init__,
# like connecting to a database or writing into a file? for that you can
# use the __post_init__ method.

from dataclasses import dataclass

@dataclass
class Guest:
    name: str
    age: int
    # in this case we use __post__init__ to validate guest age
    def __post__init__(self):
        if self.age < 18:
            raise TypeError('Guest must be over 18')
